from flask import Blueprint, request, jsonify
from services.connection_manager import manager
from services.schema_indexer import indexer
from services.llm_service import chat, resolve_references
from services import mysql_service, mongo_service, elasticsearch_service
import json
import datetime

chat_bp = Blueprint("chat", __name__)

_SERVICE_MAP = {
    "mysql": mysql_service,
    "mongodb": mongo_service,
    "elasticsearch": elasticsearch_service,
}


class _Encoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, (datetime.date, datetime.datetime)):
            return o.isoformat()
        if isinstance(o, datetime.timedelta):
            return str(o)
        if isinstance(o, bytes):
            return o.decode("utf-8", errors="replace")
        if isinstance(o, set):
            return list(o)
        return super().default(o)


@chat_bp.route("/send", methods=["POST"])
def send_message():
    data = request.get_json()
    conn_id = data.get("conn_id")
    database = data.get("database")
    messages = data.get("messages", [])

    if not conn_id or not database or not messages:
        return jsonify({"error": "conn_id, database, and messages are required"}), 400

    db_type = manager.get_db_type(conn_id)
    schemas = indexer.get_schemas(conn_id, database)

    # Resolve @/# references in the latest user message
    if messages and messages[-1]["role"] == "user":
        messages[-1]["content"] = resolve_references(messages[-1]["content"], schemas)

    schema_text = indexer.build_schema_text(conn_id, database)

    try:
        result = chat(messages, schema_text, db_type)
        return jsonify(result)
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@chat_bp.route("/execute", methods=["POST"])
def execute_generated():
    """Execute a query generated by the LLM."""
    data = request.get_json()
    conn_id = data.get("conn_id")
    database = data.get("database")
    query_text = data.get("query", "").strip()

    if not conn_id or not query_text:
        return jsonify({"error": "conn_id and query are required"}), 400

    db_type = manager.get_db_type(conn_id)
    svc = _SERVICE_MAP.get(db_type)
    if not svc:
        return jsonify({"error": f"Unsupported type: {db_type}"}), 400

    try:
        result = svc.execute_query(conn_id, query_text, database)
        return _Encoder().encode(result), 200, {"Content-Type": "application/json"}
    except Exception as e:
        return jsonify({"error": str(e)}), 400
